name: kantan
description: "An app for distributing textbook audio resources."
publish_to: 'none'
version: 0.8.0+0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  demo_assets:
    path: ../demo_assets/
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  mockito: ^5.4.4
  riverpod_annotation: ^2.3.5
  envied: ^0.5.4+1
  shared_preferences: ^2.3.2
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  just_audio_platform_interface: ^4.3.0
  just_audio: ^0.9.41
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3
  path_provider: ^2.1.5
  flutter_localized_locales: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  plugin_platform_interface: ^2.1.8
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
