name: kantan
description: "An app for distributing textbook audio resources."
publish_to: 'none'
version: 0.8.0+0

environment:
  sdk: ^3.8.1

dependencies:

  flutter:
    sdk: flutter
  path: ^1.9.0
  demo_assets:
    path: ../demo_assets/
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  mockito: ^5.4.4
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  just_audio_platform_interface: ^4.3.0
  just_audio: ^0.9.41
  rxdart: ^0.28.0
  audio_video_progress_bar: ^2.0.3
  path_provider: ^2.1.5
  flutter_localized_locales: ^2.0.5
  intl: ^0.20.2
  scroll_to_index: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flex_color_scheme: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.13
  plugin_platform_interface: ^2.1.8
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Atkinson Hyperlegible Next
      fonts:
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-Regular.otf
          weight: 400
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-RegularItalic.otf
          weight: 400
          style: italic
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-Bold.otf
          weight: 700
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-BoldItalic.otf
          weight: 700
          style: italic
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-ExtraBold.otf
          weight: 800
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-ExtraLight.otf
          weight: 200
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-Light.otf
          weight: 300
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-LightItalic.otf
          weight: 300
          style: italic
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-Medium.otf
          weight: 500
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-MediumItalic.otf
          weight: 500
          style: italic
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-SemiBold.otf
          weight: 600
          style: normal
        - asset: packages/demo_assets/fonts/AtkinsonHyperlegibleNext-SemiBoldItalic.otf
          weight: 600
          style: italic
