name: kantan
description: "An app for distributing textbook audio resources."
publish_to: 'none'
version: 0.8.0+0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  demo_assets:
    path: ../demo_assets/
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  mockito: ^5.4.4
  riverpod_annotation: ^2.3.5
  envied: ^0.5.4+1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
